sources:      
############################# Production Sources #################################
  - name: input_data
    description: pipeml input data
    #database: db
    schema: raw
    tables:
      - name: carprice_assignment
      

